name: obs-cli
base: core20
adopt-info: obs-cli
summary: Remote control OBS from the command line
description: |
 obs-cli is a thin wrapper around obs-websocket-js, which in turn is a wrapper
 around obs-websocket. It supports authentication and everything else that
 obs-websocket provides.

    Usage: obs-cli [options] <request[=arguments]...>
    
    Remote control OBS from the command line.
    
    Arguments:
      request[=arguments]        a request name (for example, ‘GetRecordingFolder’), optionally followed by arguments (for example, ‘SetRecordingFolder='{ "rec-folder":
                                 "/tmp/" }'’) (see https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md for the complete list of requests
                                 and their arguments)
    
    Options:
      -a, --address <address>    the address to the machine in which OBS is running and the port configured in OBS under Tools > WebSockets Server Settings (default:
                                 "localhost:4444")
      -p, --password <password>  the password configured in OBS under Tools > WebSockets Server Settings
      -f, --field <field>        project a field out of the OBS response, for example, given an OBS response of ‘[{ ..., "streaming": false, ...}]’ and a <field> of
                                 ‘0.streaming’, obs-cli outputs just ‘false’; this is a convenience for applications that need only one part of the response
      -V, --version              output the version number
      -h, --help                 display help for command

grade: stable
confinement: strict

parts:
  obs-cli:
    plugin: npm
    source: https://github.com/leafac/obs-cli.git
    source-tag: v2.2.3
    npm-node-version: 15.9.0
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags)"
    prime:
      - -bin/np*
      - -include
      - -lib/node_modules/npm/changelogs
      - -lib/node_modules/npm/docs
      - -lib/node_modules/npm/man

apps:
  obs-cli:
    command: bin/obs-cli
    plugs:
      - home
      - network
      - removable-media
